clear all; close all; clc
load gTruth.mat;

imds = imageDatastore(gTruth.DataSource.Source);
classNames = ["BG","red","black","purple"];
pxds = pixelLabelDatastore(gTruth);

% --- 训练/验证划分 ---
rng(42);
numFiles = numel(imds.Files);
shuffledIdx = randperm(numFiles);
numTrain = round(0.8 * numFiles);
trainIdx = shuffledIdx(1:numTrain);
valIdx = shuffledIdx(numTrain+1:end);

imdsTrain = subset(imds, trainIdx);
imdsVal = subset(imds, valIdx);
pxdsTrain = subset(pxds, trainIdx);
pxdsVal = subset(pxds, valIdx);

% --- 类别权重 ---
tbl = countEachLabel(pxdsTrain);
frequency = tbl.PixelCount / sum(tbl.PixelCount);
classWeights = median(frequency) ./ frequency;

% --- 网络 ---
imageSize = [240 432 3];
numClasses = numel(classNames);
lgraph = deeplabv3plusLayers(imageSize, numClasses, "mobilenetv2");

pxLayer = pixelClassificationLayer('Name','labels',...
    'Classes', classNames, 'ClassWeights', classWeights);
lgraph = replaceLayer(lgraph, lgraph.Layers(end).Name, pxLayer);

% --- 数据增强 ---
augmenter = imageDataAugmenter(...
    'RandXReflection', true, ...
    'RandYReflection', true, ...
    'RandRotation', [-15 15], ...
    'RandXTranslation', [-15 15], ...
    'RandYTranslation', [-15 15], ...
    'RandXScale', [0.85 1.15], ...
    'RandYScale', [0.85 1.15]);

pximdsTrain = pixelLabelImageDatastore(imdsTrain, pxdsTrain, ...
    'OutputSize', imageSize, ...
    'ColorPreprocessing', 'gray2rgb', ...
    'DataAugmentation', augmenter);

pximdsVal = pixelLabelImageDatastore(imdsVal, pxdsVal, ...
    'OutputSize', imageSize, ...
    'ColorPreprocessing', 'gray2rgb');

% --- 训练参数 ---
opts = trainingOptions("adam", ...
    'ExecutionEnvironment', 'cpu', ...
    'InitialLearnRate', 1e-4, ...
    'LearnRateSchedule', 'piecewise', ...
    'LearnRateDropFactor', 0.5, ...
    'LearnRateDropPeriod', 10, ...
    'L2Regularization', 5e-4, ...
    'MiniBatchSize', 2, ...
    'MaxEpochs', 40, ...
    'Shuffle', 'every-epoch', ...
    'ValidationData', pximdsVal, ...
    'ValidationFrequency', 30, ...
    'ValidationPatience', 8, ...
    'Plots', 'training-progress', ...
    'Verbose', true);

[net, info] = trainNetwork(pximdsTrain, lgraph, opts);
%save('3DtrainedMobilenetv250-50.mat', 'net');
%save('3DtrainedMobilenetv250-50.mat', 'info');
